//go:build !ignore_autogenerated

/*
Copyright The Platform Mesh Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/operator/v1alpha1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheServer) DeepCopyInto(out *CacheServer) {
	*out = *in
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(operatorv1alpha1.CacheServerTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheServer.
func (in *CacheServer) DeepCopy() *CacheServer {
	if in == nil {
		return nil
	}
	out := new(CacheServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdSpec) DeepCopyInto(out *EtcdSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdSpec.
func (in *EtcdSpec) DeepCopy() *EtcdSpec {
	if in == nil {
		return nil
	}
	out := new(EtcdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Exposure) DeepCopyInto(out *Exposure) {
	*out = *in
	if in.IngressRefs != nil {
		in, out := &in.IngressRefs, &out.IngressRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Exposure.
func (in *Exposure) DeepCopy() *Exposure {
	if in == nil {
		return nil
	}
	out := new(Exposure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrontProxy) DeepCopyInto(out *FrontProxy) {
	*out = *in
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(operatorv1alpha1.FrontProxyTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Exposure.DeepCopyInto(&out.Exposure)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrontProxy.
func (in *FrontProxy) DeepCopy() *FrontProxy {
	if in == nil {
		return nil
	}
	out := new(FrontProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfraComponent) DeepCopyInto(out *InfraComponent) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfraComponent.
func (in *InfraComponent) DeepCopy() *InfraComponent {
	if in == nil {
		return nil
	}
	out := new(InfraComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfraSpec) DeepCopyInto(out *InfraSpec) {
	*out = *in
	if in.EtcdDruid != nil {
		in, out := &in.EtcdDruid, &out.EtcdDruid
		*out = new(InfraComponent)
		(*in).DeepCopyInto(*out)
	}
	if in.CertManager != nil {
		in, out := &in.CertManager, &out.CertManager
		*out = new(InfraComponent)
		(*in).DeepCopyInto(*out)
	}
	if in.GatewayAPI != nil {
		in, out := &in.GatewayAPI, &out.GatewayAPI
		*out = new(InfraComponent)
		(*in).DeepCopyInto(*out)
	}
	if in.Traefik != nil {
		in, out := &in.Traefik, &out.Traefik
		*out = new(InfraComponent)
		(*in).DeepCopyInto(*out)
	}
	if in.Observability != nil {
		in, out := &in.Observability, &out.Observability
		*out = new(InfraComponent)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfraSpec.
func (in *InfraSpec) DeepCopy() *InfraSpec {
	if in == nil {
		return nil
	}
	out := new(InfraSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressStack) DeepCopyInto(out *IngressStack) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressStack.
func (in *IngressStack) DeepCopy() *IngressStack {
	if in == nil {
		return nil
	}
	out := new(IngressStack)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Module) DeepCopyInto(out *Module) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Module.
func (in *Module) DeepCopy() *Module {
	if in == nil {
		return nil
	}
	out := new(Module)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Module) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleList) DeepCopyInto(out *ModuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Module, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleList.
func (in *ModuleList) DeepCopy() *ModuleList {
	if in == nil {
		return nil
	}
	out := new(ModuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSetup) DeepCopyInto(out *ModuleSetup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSetup.
func (in *ModuleSetup) DeepCopy() *ModuleSetup {
	if in == nil {
		return nil
	}
	out := new(ModuleSetup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleSetup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSetupList) DeepCopyInto(out *ModuleSetupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModuleSetup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSetupList.
func (in *ModuleSetupList) DeepCopy() *ModuleSetupList {
	if in == nil {
		return nil
	}
	out := new(ModuleSetupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModuleSetupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSetupSpec) DeepCopyInto(out *ModuleSetupSpec) {
	*out = *in
	out.PlatformMeshRef = in.PlatformMeshRef
	out.ModuleRef = in.ModuleRef
	if in.KcpContent != nil {
		in, out := &in.KcpContent, &out.KcpContent
		*out = make([]ResourceRef, len(*in))
		copy(*out, *in)
	}
	if in.Workspaces != nil {
		in, out := &in.Workspaces, &out.Workspaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KubeconfigRefs != nil {
		in, out := &in.KubeconfigRefs, &out.KubeconfigRefs
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSetupSpec.
func (in *ModuleSetupSpec) DeepCopy() *ModuleSetupSpec {
	if in == nil {
		return nil
	}
	out := new(ModuleSetupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSetupStatus) DeepCopyInto(out *ModuleSetupStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.NextReconcileTime.DeepCopyInto(&out.NextReconcileTime)
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSetupStatus.
func (in *ModuleSetupStatus) DeepCopy() *ModuleSetupStatus {
	if in == nil {
		return nil
	}
	out := new(ModuleSetupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleSpec) DeepCopyInto(out *ModuleSpec) {
	*out = *in
	out.PlatformMeshRef = in.PlatformMeshRef
	if in.OCM != nil {
		in, out := &in.OCM, &out.OCM
		*out = new(OCMRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleSpec.
func (in *ModuleSpec) DeepCopy() *ModuleSpec {
	if in == nil {
		return nil
	}
	out := new(ModuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleStatus) DeepCopyInto(out *ModuleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.NextReconcileTime.DeepCopyInto(&out.NextReconcileTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleStatus.
func (in *ModuleStatus) DeepCopy() *ModuleStatus {
	if in == nil {
		return nil
	}
	out := new(ModuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCMRepository) DeepCopyInto(out *OCMRepository) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCMRepository.
func (in *OCMRepository) DeepCopy() *OCMRepository {
	if in == nil {
		return nil
	}
	out := new(OCMRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformMesh) DeepCopyInto(out *PlatformMesh) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformMesh.
func (in *PlatformMesh) DeepCopy() *PlatformMesh {
	if in == nil {
		return nil
	}
	out := new(PlatformMesh)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformMesh) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformMeshList) DeepCopyInto(out *PlatformMeshList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlatformMesh, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformMeshList.
func (in *PlatformMeshList) DeepCopy() *PlatformMeshList {
	if in == nil {
		return nil
	}
	out := new(PlatformMeshList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformMeshList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformMeshSpec) DeepCopyInto(out *PlatformMeshSpec) {
	*out = *in
	in.OCM.DeepCopyInto(&out.OCM)
	in.Topology.DeepCopyInto(&out.Topology)
	in.Infra.DeepCopyInto(&out.Infra)
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = make([]IngressStack, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformMeshSpec.
func (in *PlatformMeshSpec) DeepCopy() *PlatformMeshSpec {
	if in == nil {
		return nil
	}
	out := new(PlatformMeshSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformMeshStatus) DeepCopyInto(out *PlatformMeshStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.NextReconcileTime.DeepCopyInto(&out.NextReconcileTime)
	if in.ShardAssignments != nil {
		in, out := &in.ShardAssignments, &out.ShardAssignments
		*out = make([]ShardAssignment, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformMeshStatus.
func (in *PlatformMeshStatus) DeepCopy() *PlatformMeshStatus {
	if in == nil {
		return nil
	}
	out := new(PlatformMeshStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRef) DeepCopyInto(out *ResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRef.
func (in *ResourceRef) DeepCopy() *ResourceRef {
	if in == nil {
		return nil
	}
	out := new(ResourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RootShard) DeepCopyInto(out *RootShard) {
	*out = *in
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(operatorv1alpha1.RootShardTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Etcd.DeepCopyInto(&out.Etcd)
	in.Exposure.DeepCopyInto(&out.Exposure)
	in.VirtualWorkspaces.DeepCopyInto(&out.VirtualWorkspaces)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RootShard.
func (in *RootShard) DeepCopy() *RootShard {
	if in == nil {
		return nil
	}
	out := new(RootShard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardAssignment) DeepCopyInto(out *ShardAssignment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardAssignment.
func (in *ShardAssignment) DeepCopy() *ShardAssignment {
	if in == nil {
		return nil
	}
	out := new(ShardAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardGroup) DeepCopyInto(out *ShardGroup) {
	*out = *in
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(operatorv1alpha1.ShardTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Etcd.DeepCopyInto(&out.Etcd)
	if in.Exposure != nil {
		in, out := &in.Exposure, &out.Exposure
		*out = new(Exposure)
		(*in).DeepCopyInto(*out)
	}
	in.VirtualWorkspaces.DeepCopyInto(&out.VirtualWorkspaces)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardGroup.
func (in *ShardGroup) DeepCopy() *ShardGroup {
	if in == nil {
		return nil
	}
	out := new(ShardGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Topology) DeepCopyInto(out *Topology) {
	*out = *in
	in.RootShard.DeepCopyInto(&out.RootShard)
	if in.ShardGroups != nil {
		in, out := &in.ShardGroups, &out.ShardGroups
		*out = make([]ShardGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FrontProxies != nil {
		in, out := &in.FrontProxies, &out.FrontProxies
		*out = make([]FrontProxy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CacheServers != nil {
		in, out := &in.CacheServers, &out.CacheServers
		*out = make([]CacheServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Topology.
func (in *Topology) DeepCopy() *Topology {
	if in == nil {
		return nil
	}
	out := new(Topology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualWorkspaceSpec) DeepCopyInto(out *VirtualWorkspaceSpec) {
	*out = *in
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(operatorv1alpha1.VirtualWorkspaceTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Exposure.DeepCopyInto(&out.Exposure)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualWorkspaceSpec.
func (in *VirtualWorkspaceSpec) DeepCopy() *VirtualWorkspaceSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualWorkspaceSpec)
	in.DeepCopyInto(out)
	return out
}
