# Copyright The Platform Mesh Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: deploy.platform-mesh.io/v1alpha1
kind: RootShardTemplate
metadata:
  name: root
  namespace: platform-mesh-system
spec:
  replicas: 2
  etcd:
    endpoints:
      - '"https://etcd." + platformMesh + ".svc:2379"'
    prefix: '"/" + platformMesh + "/root"'
---
apiVersion: deploy.platform-mesh.io/v1alpha1
kind: ShardTemplate
metadata:
  name: default
  namespace: platform-mesh-system
spec:
  replicas: 2
  etcd:
    endpoints:
      - '"https://etcd." + platformMesh + ".svc:2379"'
    prefix: '"/" + platformMesh + "/" + component + "/" + cluster'
---
apiVersion: deploy.platform-mesh.io/v1alpha1
kind: PlatformMesh
metadata:
  name: platform-mesh-sample
  namespace: platform-mesh-system
spec:
  version: 1.0.0
  ocm:
    url: ghcr.io/platform-mesh
    component: github.com/platform-mesh/platform-mesh
  topology:
    rootShard:
      name: root
      templateRef:
        name: root
      exposure:
        hostnameTemplate: '"root." + cluster + ".example.com"'
        port: 6443
      virtualWorkspaces:
        mode: Embedded
        exposure:
          hostnameTemplate: '"vw-root." + cluster + ".example.com"'
          port: 6443
    shardGroups:
      - name: default
        templateRef:
          name: default
        exposure:
          hostnameTemplate: 'component + "." + cluster + ".example.com"'
          port: 6443
        virtualWorkspaces:
          mode: Embedded
          exposure:
            hostnameTemplate: '"vw." + component + "." + cluster + ".example.com"'
            port: 6443
    frontProxy:
      name: fp
      exposure:
        hostnameTemplate: '"kcp.example.com"'
        port: 6443
  ingress:
    - name: default
      type: gatewayapi
      gatewayAPI:
        gatewayName: eg
        gatewayNamespace: envoy-gateway-system
        sectionName: passthrough
